### ISSUE TITLE
Stale Quickdocs references

### ISSUE THREAD

**Issue by phoe** [Hexstream/www.hexstreamsoft.com#1]
https://github.com/Hexstream/www.hexstreamsoft.com/blob/f4545ca0c3c729b62506b94a668b83284b42c313/libraries/external-pages-xref/index.html#L50

Links should be easily replaceable with Quickref.

**Comment by Hexstream** [comment]
Thank you for the reminder.

While I appreciate the effort put into these sites, I don't think they provide substantial value in the context of [my libraries](https://www.hexstreamsoft.com/libraries/), since I usually provide a thin README plus extensive hand-written HTML documentation. (Especially in my newer libraries. Many of my older libraries would be due for an update.) I was linking to Quickdocs mostly for the dependencies/reverse-dependencies feature.

As a point of comparison, see [the official documentation for definitions-systems](https://www.hexstreamsoft.com/libraries/definitions-systems/) VS [the corresponding page in quickref](https://quickref.common-lisp.net/definitions-systems.html). I think hand-written documentation is a vastly superior approach to auto-generated crap. Maybe it would be possible to combine the best aspects of both worlds, but I have seen nothing that even comes close to achieving that yet.

As such, I just decided to remove the Quickdocs references.
